### ISSUE TITLE
Unable to edit organization info thru /admin unless Firebase is open

### ISSUE THREAD

**Issue by marcumvaughan** [zendesk/linksf#330]
Hi, 
This might be a problem with my setup rather than a bug but I can't edit organization information through the app's admin page unless Firebase is open (i.e. the database rules are read & write true for everybody).  

Steps to reproduce:  I pulled down the latest from the open-referral branch, created a firebase account and a firebase user, and updated config.js with my firebase acount info.  If I start the app and go to /admin I am prompted for a login.  If I supply a bad login or an incorrect password I get an error message (good).  If I supply the right login info I get to the admin page and can select an existing organization for editing.  The editing page opens, I change values, and click submit, but the changes do not show up in the firebase database.  However, they do show up if I change the rules from  ".write": "auth != null" to  ".write": "true".

**Comment by craig-day** [comment]
Hey @marcumvaughan thanks for bringing this up.  What you described is unfortunate, but expected behavior right now.  We haven't gotten to permissions and permission management yet. Our primary focus right now is to get the non-administrative side of things to have full feature parity to master before jumping into the admin pages.  

Thanks for your interest in the project and please bear with us while we continue our transition.

**Comment by roseleaf** [comment]
https://github.com/zendesk/linksf/pull/337
